# Exception class and properties

The [Exception](http://dotnet.github.io/api/System.Exception.html) class is the base class from which exceptions inherit. Most exception objects are instances of some derived class of **Exception**, but you can throw any object that derives from the [Object](http://dotnet.github.io/api/System.Object.html) class as an exception. Note that not all languages support throwing and catching objects that do not derive from **Exception**. In nearly all cases, it is recommended to throw and catch only **Exception** objects.

The **Exception** class has the following properties to help make understanding an exception easier.

| Property Name | Description |
| ------------- | ----------- |
| [Data](http://dotnet.github.io/api/System.Exception.html#System_Exception_Data) | An [IDictionary](http://dotnet.github.io/api/System.Collections.IDictionary.html) that holds arbitrary data in key-value pairs. |
| [HelpLink](http://dotnet.github.io/api/System.Exception.html#System_Exception_HelpLink) | Can hold a URL (or URN) to a help file that provides extensive information about the cause of an exception. |
| [HResult](http://dotnet.github.io/api/System.Exception.html#System_Exception_HResult) | Gets or sets an HResult, a coded numerical value that is assigned to a specific exception. |
| [InnerException](http://dotnet.github.io/api/System.Exception.html#System_Exception_InnerException) | This property can be used to create and preserve a series of exceptions during exception handling. You can use it to create a new exception that contains previously caught exceptions. The original exception can be captured by the second exception in the **InnerException** property, allowing code that handles the second exception to examine the additional information. For example, suppose you have a method that receives an argument that's improperly formatted.  The code tries to read the argument, but an exception is thrown. The method catches the exception and throws a [FormatException](http://dotnet.github.io/api/System.FormatException.html). To improve the caller's ability to determine the reason an exception is thrown, it is sometimes desirable for a method to catch an exception thrown by a helper routine and then throw an exception more indicative of the error that has occurred. A new and more meaningful exception can be created, where the inner exception reference can be set to the original exception. This more meaningful exception can then be thrown to the caller. Note that with this functionality, you can create a series of linked exceptions that ends with the exception that was thrown first. |
| [Message](http://dotnet.github.io/api/System.Exception.html#System_Exception_Message) | Provides details about the cause of an exception.
| [Source](http://dotnet.github.io/api/System.Exception.html#System_Exception_Source) | Gets or sets the name of the application or the object that causes the error. |
| [StackTrace](http://dotnet.github.io/api/System.Exception.html#System_Exception_StackTrace) | Contains a stack trace that can be used to determine where an error occurred. The stack trace includes the source file name and program line number if debugging information is available. |

Most of the classes that inherit from **Exception** do not implement additional members or provide additional functionality; they simply inherit from **Exception**. Therefore, the most important information for an exception can be found in the hierarchy of exceptions, the exception name, and the information contained in the exception.
